import { db } from "./index";
import {
  users,
  ports,
  berths,
  vessels,
  cranes,
  yards,
  vesselSchedules,
  congestionPredictions,
  routingRecommendations,
  berthAssignments,
  craneAssignments,
  operationPlans,
  alerts,
} from "./schema";
import bcrypt from "bcryptjs";

export async function runSeed() {
  console.log("Seeding database...");

  // Clear existing data
  await db.delete(alerts);
  await db.delete(operationPlans);
  await db.delete(craneAssignments);
  await db.delete(berthAssignments);
  await db.delete(routingRecommendations);
  await db.delete(congestionPredictions);
  await db.delete(vesselSchedules);
  await db.delete(vessels);
  await db.delete(cranes);
  await db.delete(berths);
  await db.delete(yards);
  await db.delete(ports);
  await db.delete(users);

  // 1. Users
  const passwordHash = await bcrypt.hash("Admin@123", 10);
  const [adminUser, supervisorUser] = await db
    .insert(users)
    .values([
      {
        name: "Capt. Arthur Miller",
        email: "admin@portdemo.com",
        password_hash: passwordHash,
        role: "Admin",
      },
      {
        name: "Elena Rostova",
        email: "supervisor@portdemo.com",
        password_hash: passwordHash,
        role: "Port Supervisor",
      },
      {
        name: "David Chen",
        email: "operator@portdemo.com",
        password_hash: passwordHash,
        role: "Operator",
      },
    ])
    .returning();

  // 2. Ports
  const [portLAX] = await db
    .insert(ports)
    .values([
      {
        code: "USLAX",
        name: "Port of LA / Long Beach Complex",
        country: "United States",
        total_berths: 10,
        total_cranes: 16,
        yard_capacity_teu: 145000,
      },
      {
        code: "SGSIN",
        name: "Port of Singapore (Tuas Mega Port)",
        country: "Singapore",
        total_berths: 14,
        total_cranes: 22,
        yard_capacity_teu: 210000,
      },
      {
        code: "NLRTM",
        name: "Port of Rotterdam (Maasvlakte II)",
        country: "Netherlands",
        total_berths: 12,
        total_cranes: 18,
        yard_capacity_teu: 180000,
      },
    ])
    .returning();

  const portId = portLAX.id;

  // 3. Berths (10 Berths)
  const insertedBerths = await db
    .insert(berths)
    .values([
      {
        port_id: portId,
        berth_code: "B01",
        name: "Berth 01 - Pier 400 Deepwater",
        capacity: 22000,
        max_draft: "17.5",
        current_utilisation: 78,
        status: "Occupied",
        available_cranes: 1,
      },
      {
        port_id: portId,
        berth_code: "B02",
        name: "Berth 02 - Pier 400 North",
        capacity: 18500,
        max_draft: "16.8",
        current_utilisation: 85,
        status: "Occupied",
        available_cranes: 1,
      },
      {
        port_id: portId,
        berth_code: "B03",
        name: "Berth 03 - Middle Harbor Basin",
        capacity: 16000,
        max_draft: "16.0",
        current_utilisation: 42,
        status: "Available",
        available_cranes: 3,
      },
      {
        port_id: portId,
        berth_code: "B04",
        name: "Berth 04 - Pier G Super Terminal",
        capacity: 24000,
        max_draft: "18.0",
        current_utilisation: 96,
        status: "High Congestion",
        available_cranes: 0,
      },
      {
        port_id: portId,
        berth_code: "B05",
        name: "Berth 05 - Pier J Transshipment",
        capacity: 20000,
        max_draft: "17.2",
        current_utilisation: 92,
        status: "High Congestion",
        available_cranes: 0,
      },
      {
        port_id: portId,
        berth_code: "B06",
        name: "Berth 06 - Pier E Automated Quay",
        capacity: 21000,
        max_draft: "17.0",
        current_utilisation: 34,
        status: "Available",
        available_cranes: 4,
      },
      {
        port_id: portId,
        berth_code: "B07",
        name: "Berth 07 - West Basin Quay A",
        capacity: 14000,
        max_draft: "15.5",
        current_utilisation: 65,
        status: "Occupied",
        available_cranes: 2,
      },
      {
        port_id: portId,
        berth_code: "B08",
        name: "Berth 08 - West Basin Quay B",
        capacity: 12500,
        max_draft: "15.0",
        current_utilisation: 15,
        status: "Available",
        available_cranes: 3,
      },
      {
        port_id: portId,
        berth_code: "B09",
        name: "Berth 09 - Terminal Island South",
        capacity: 19000,
        max_draft: "16.5",
        current_utilisation: 0,
        status: "Maintenance",
        available_cranes: 0,
      },
      {
        port_id: portId,
        berth_code: "B10",
        name: "Berth 10 - Cerritos Channel Slip",
        capacity: 10500,
        max_draft: "14.0",
        current_utilisation: 20,
        status: "Available",
        available_cranes: 2,
      },
    ])
    .returning();

  const berthMap = new Map(insertedBerths.map((b) => [b.berth_code, b.id]));

  // 4. Yards (5 Zones)
  await db.insert(yards).values([
    {
      port_id: portId,
      yard_code: "YARD-A",
      name: "Yard A - Import Express Staging",
      capacity: 35000,
      current_occupancy: 31500, // 90%
      status: "Critical",
      zone_type: "Import Staging",
    },
    {
      port_id: portId,
      yard_code: "YARD-B",
      name: "Yard B - Export Consolidation Hub",
      capacity: 40000,
      current_occupancy: 32800, // 82%
      status: "Near Capacity",
      zone_type: "Export Staging",
    },
    {
      port_id: portId,
      yard_code: "YARD-C",
      name: "Yard C - Cold Chain Reefer Yard",
      capacity: 18000,
      current_occupancy: 13500, // 75%
      status: "Normal",
      zone_type: "Reefer Yard",
    },
    {
      port_id: portId,
      yard_code: "YARD-D",
      name: "Yard D - Empty Container Depots",
      capacity: 28000,
      current_occupancy: 25200, // 90%
      status: "Critical",
      zone_type: "Empty Stacking",
    },
    {
      port_id: portId,
      yard_code: "YARD-E",
      name: "Yard E - Intermodal Rail Transfer",
      capacity: 24000,
      current_occupancy: 17280, // 72%
      status: "Normal",
      zone_type: "Rail Intermodal",
    },
  ]);

  // 5. Cranes (16 Cranes)
  const insertedCranes = await db
    .insert(cranes)
    .values([
      {
        port_id: portId,
        crane_code: "C01",
        type: "STS Super Post-Panamax",
        capacity: 48,
        status: "Working",
        maintenance_status: "Operational",
        assigned_berth_id: berthMap.get("B04"),
        utilisation: 94,
      },
      {
        port_id: portId,
        crane_code: "C02",
        type: "STS Super Post-Panamax",
        capacity: 48,
        status: "Working",
        maintenance_status: "Operational",
        assigned_berth_id: berthMap.get("B04"),
        utilisation: 91,
      },
      {
        port_id: portId,
        crane_code: "C03",
        type: "STS Super Post-Panamax",
        capacity: 45,
        status: "Working",
        maintenance_status: "Operational",
        assigned_berth_id: berthMap.get("B01"),
        utilisation: 82,
      },
      {
        port_id: portId,
        crane_code: "C04",
        type: "STS Super Post-Panamax",
        capacity: 45,
        status: "Working",
        maintenance_status: "Operational",
        assigned_berth_id: berthMap.get("B01"),
        utilisation: 86,
      },
      {
        port_id: portId,
        crane_code: "C05",
        type: "STS Post-Panamax",
        capacity: 38,
        status: "Working",
        maintenance_status: "Operational",
        assigned_berth_id: berthMap.get("B02"),
        utilisation: 88,
      },
      {
        port_id: portId,
        crane_code: "C06",
        type: "STS Post-Panamax",
        capacity: 38,
        status: "Working",
        maintenance_status: "Operational",
        assigned_berth_id: berthMap.get("B05"),
        utilisation: 95,
      },
      {
        port_id: portId,
        crane_code: "C07",
        type: "STS Super Post-Panamax",
        capacity: 46,
        status: "Maintenance",
        maintenance_status: "In Repair",
        assigned_berth_id: berthMap.get("B09"),
        utilisation: 0,
      },
      {
        port_id: portId,
        crane_code: "C08",
        type: "STS Post-Panamax",
        capacity: 40,
        status: "Available",
        maintenance_status: "Operational",
        assigned_berth_id: berthMap.get("B06"),
        utilisation: 25,
      },
      {
        port_id: portId,
        crane_code: "C09",
        type: "STS Post-Panamax",
        capacity: 40,
        status: "Available",
        maintenance_status: "Operational",
        assigned_berth_id: berthMap.get("B06"),
        utilisation: 20,
      },
      {
        port_id: portId,
        crane_code: "C10",
        type: "STS Post-Panamax",
        capacity: 38,
        status: "Available",
        maintenance_status: "Operational",
        assigned_berth_id: berthMap.get("B06"),
        utilisation: 15,
      },
      {
        port_id: portId,
        crane_code: "C11",
        type: "STS Super Post-Panamax",
        capacity: 46,
        status: "Available",
        maintenance_status: "Operational",
        assigned_berth_id: berthMap.get("B06"),
        utilisation: 18,
      },
      {
        port_id: portId,
        crane_code: "C12",
        type: "Mobile Harbour Crane",
        capacity: 32,
        status: "Working",
        maintenance_status: "Operational",
        assigned_berth_id: berthMap.get("B07"),
        utilisation: 70,
      },
      {
        port_id: portId,
        crane_code: "C13",
        type: "Mobile Harbour Crane",
        capacity: 32,
        status: "Available",
        maintenance_status: "Scheduled Inspection",
        assigned_berth_id: berthMap.get("B08"),
        utilisation: 10,
      },
      {
        port_id: portId,
        crane_code: "C14",
        type: "Mobile Harbour Crane",
        capacity: 30,
        status: "Available",
        maintenance_status: "Operational",
        assigned_berth_id: berthMap.get("B03"),
        utilisation: 30,
      },
      {
        port_id: portId,
        crane_code: "C15",
        type: "RTG Rail Mounted",
        capacity: 35,
        status: "Available",
        maintenance_status: "Operational",
        assigned_berth_id: berthMap.get("B03"),
        utilisation: 35,
      },
      {
        port_id: portId,
        crane_code: "C16",
        type: "Mobile Harbour Crane",
        capacity: 28,
        status: "Offline",
        maintenance_status: "Overhaul Needed",
        assigned_berth_id: berthMap.get("B10"),
        utilisation: 0,
      },
    ])
    .returning();

  // 6. Vessels (28 realistic vessels)
  const now = new Date();
  const h = (hours: number) => new Date(now.getTime() + hours * 3600 * 1000);

  const rawVessels = [
    {
      name: "MV Ocean Star",
      imo_number: "IMO9821453",
      eta: h(-6),
      etd: h(34),
      container_volume: 16800,
      vessel_size: "Ultra Large",
      priority: "Critical",
      status: "Waiting",
      assigned_berth_id: berthMap.get("B04") || null,
      destination: "Los Angeles",
      origin: "Shanghai Port",
      draft: "16.8",
      waiting_time_hours: "5.2",
    },
    {
      name: "MSC Horizon",
      imo_number: "IMO9745812",
      eta: h(-12),
      etd: h(18),
      container_volume: 19200,
      vessel_size: "Ultra Large",
      priority: "High",
      status: "Unloading",
      assigned_berth_id: berthMap.get("B01") || null,
      destination: "Long Beach",
      origin: "Ningbo-Zhoushan",
      draft: "17.2",
      waiting_time_hours: "2.1",
    },
    {
      name: "Ever Given II",
      imo_number: "IMO9811000",
      eta: h(-18),
      etd: h(24),
      container_volume: 20124,
      vessel_size: "Ultra Large",
      priority: "High",
      status: "Loading",
      assigned_berth_id: berthMap.get("B02") || null,
      destination: "Yokohama",
      origin: "Shenzhen Port",
      draft: "16.4",
      waiting_time_hours: "1.8",
    },
    {
      name: "CMA CGM Palais Royal",
      imo_number: "IMO9839181",
      eta: h(-4),
      etd: h(40),
      container_volume: 23000,
      vessel_size: "Ultra Large",
      priority: "Critical",
      status: "Waiting",
      assigned_berth_id: berthMap.get("B05") || null,
      destination: "Los Angeles",
      origin: "Busan New Port",
      draft: "17.4",
      waiting_time_hours: "6.8",
    },
    {
      name: "Maersk Mc-Kinney Moller",
      imo_number: "IMO9619907",
      eta: h(4),
      etd: h(48),
      container_volume: 18270,
      vessel_size: "Ultra Large",
      priority: "High",
      status: "Scheduled",
      assigned_berth_id: berthMap.get("B04") || null,
      destination: "Los Angeles",
      origin: "Qingdao Port",
      draft: "16.5",
      waiting_time_hours: "4.5",
    },
    {
      name: "COSCO Shipping Universe",
      imo_number: "IMO9795610",
      eta: h(-2),
      etd: h(36),
      container_volume: 21237,
      vessel_size: "Ultra Large",
      priority: "High",
      status: "Arrived",
      assigned_berth_id: null,
      destination: "Long Beach",
      origin: "Tianjin Port",
      draft: "16.9",
      waiting_time_hours: "3.4",
    },
    {
      name: "Hapag-Lloyd Berlin Express",
      imo_number: "IMO9943841",
      eta: h(-14),
      etd: h(12),
      container_volume: 23664,
      vessel_size: "Ultra Large",
      priority: "Medium",
      status: "Unloading",
      assigned_berth_id: berthMap.get("B04") || null,
      destination: "Hamburg",
      origin: "Singapore Port",
      draft: "16.7",
      waiting_time_hours: "2.5",
    },
    {
      name: "ONE Apus Express",
      imo_number: "IMO9806079",
      eta: h(8),
      etd: h(56),
      container_volume: 14052,
      vessel_size: "Post-Panamax",
      priority: "Medium",
      status: "Scheduled",
      assigned_berth_id: null,
      destination: "Kobe",
      origin: "Yantian Port",
      draft: "15.8",
      waiting_time_hours: "0.0",
    },
    {
      name: "OOCL Hong Kong",
      imo_number: "IMO9776171",
      eta: h(-8),
      etd: h(28),
      container_volume: 21413,
      vessel_size: "Ultra Large",
      priority: "Critical",
      status: "Waiting",
      assigned_berth_id: berthMap.get("B05") || null,
      destination: "Los Angeles",
      origin: "Hong Kong Port",
      draft: "16.8",
      waiting_time_hours: "7.1",
    },
    {
      name: "Yang Ming Witness",
      imo_number: "IMO9708455",
      eta: h(12),
      etd: h(60),
      container_volume: 14080,
      vessel_size: "Post-Panamax",
      priority: "Medium",
      status: "Scheduled",
      assigned_berth_id: null,
      destination: "Kaohsiung",
      origin: "Keelung Port",
      draft: "15.3",
      waiting_time_hours: "0.0",
    },
    {
      name: "Hyundai Earth",
      imo_number: "IMO9725110",
      eta: h(-16),
      etd: h(10),
      container_volume: 10000,
      vessel_size: "Panamax",
      priority: "Low",
      status: "Unloading",
      assigned_berth_id: berthMap.get("B07") || null,
      destination: "Gwangyang",
      origin: "Ulsan Port",
      draft: "14.2",
      waiting_time_hours: "1.0",
    },
    {
      name: "ZIM Antwerp",
      imo_number: "IMO9407897",
      eta: h(-1),
      etd: h(30),
      container_volume: 8500,
      vessel_size: "Panamax",
      priority: "High",
      status: "Arrived",
      assigned_berth_id: null,
      destination: "Haifa",
      origin: "Shenzhen Port",
      draft: "13.9",
      waiting_time_hours: "1.2",
    },
    {
      name: "Wan Hai 515",
      imo_number: "IMO9497745",
      eta: h(16),
      etd: h(64),
      container_volume: 4500,
      vessel_size: "Feeder",
      priority: "Low",
      status: "Scheduled",
      assigned_berth_id: null,
      destination: "Taichung",
      origin: "Manila Port",
      draft: "11.5",
      waiting_time_hours: "0.0",
    },
    {
      name: "Pacific Voyager",
      imo_number: "IMO9638927",
      eta: h(-9),
      etd: h(20),
      container_volume: 6800,
      vessel_size: "Panamax",
      priority: "Medium",
      status: "Waiting",
      assigned_berth_id: null,
      destination: "Los Angeles",
      origin: "Tokyo Port",
      draft: "12.8",
      waiting_time_hours: "4.8",
    },
    {
      name: "Seaspan Amazon",
      imo_number: "IMO9630391",
      eta: h(20),
      etd: h(72),
      container_volume: 10000,
      vessel_size: "Panamax",
      priority: "Medium",
      status: "Scheduled",
      assigned_berth_id: null,
      destination: "Vancouver",
      origin: "Busan Port",
      draft: "14.0",
      waiting_time_hours: "0.0",
    },
    {
      name: "Ever Forward",
      imo_number: "IMO9850551",
      eta: h(24),
      etd: h(80),
      container_volume: 12118,
      vessel_size: "Post-Panamax",
      priority: "High",
      status: "Scheduled",
      assigned_berth_id: null,
      destination: "Oakland",
      origin: "Xiamen Port",
      draft: "15.0",
      waiting_time_hours: "0.0",
    },
    {
      name: "CMA CGM Christophe Colomb",
      imo_number: "IMO9453559",
      eta: h(-22),
      etd: h(6),
      container_volume: 13344,
      vessel_size: "Post-Panamax",
      priority: "Medium",
      status: "Completed",
      assigned_berth_id: berthMap.get("B03") || null,
      destination: "Le Havre",
      origin: "Singapore Port",
      draft: "15.2",
      waiting_time_hours: "0.8",
    },
    {
      name: "Madrid Maersk",
      imo_number: "IMO9778791",
      eta: h(30),
      etd: h(90),
      container_volume: 20568,
      vessel_size: "Ultra Large",
      priority: "Critical",
      status: "Scheduled",
      assigned_berth_id: null,
      destination: "Rotterdam",
      origin: "Tanjung Pelepas",
      draft: "16.8",
      waiting_time_hours: "0.0",
    },
    {
      name: "MSC Isabella",
      imo_number: "IMO9839284",
      eta: h(36),
      etd: h(96),
      container_volume: 23656,
      vessel_size: "Ultra Large",
      priority: "High",
      status: "Scheduled",
      assigned_berth_id: null,
      destination: "Antwerp",
      origin: "Ningbo Port",
      draft: "17.0",
      waiting_time_hours: "0.0",
    },
    {
      name: "HMM Algeciras",
      imo_number: "IMO9863297",
      eta: h(-5),
      etd: h(44),
      container_volume: 23964,
      vessel_size: "Ultra Large",
      priority: "Critical",
      status: "Waiting",
      assigned_berth_id: null,
      destination: "Los Angeles",
      origin: "Gwangyang Port",
      draft: "17.2",
      waiting_time_hours: "5.9",
    },
    {
      name: "APL Raffles",
      imo_number: "IMO9632064",
      eta: h(42),
      etd: h(100),
      container_volume: 17292,
      vessel_size: "Ultra Large",
      priority: "Medium",
      status: "Scheduled",
      assigned_berth_id: null,
      destination: "Seattle",
      origin: "Yokohama Port",
      draft: "16.0",
      waiting_time_hours: "0.0",
    },
    {
      name: "Cosco Shipping Taurus",
      imo_number: "IMO9783459",
      eta: h(-3),
      etd: h(38),
      container_volume: 20119,
      vessel_size: "Ultra Large",
      priority: "High",
      status: "Waiting",
      assigned_berth_id: berthMap.get("B04") || null,
      destination: "Long Beach",
      origin: "Shanghai Port",
      draft: "16.7",
      waiting_time_hours: "4.1",
    },
    {
      name: "CMA CGM Rivoli",
      imo_number: "IMO9839193",
      eta: h(-11),
      etd: h(26),
      container_volume: 23112,
      vessel_size: "Ultra Large",
      priority: "High",
      status: "Delayed",
      assigned_berth_id: berthMap.get("B05") || null,
      destination: "Los Angeles",
      origin: "Busan Port",
      draft: "17.1",
      waiting_time_hours: "8.3",
    },
    {
      name: "NYK Blue Jay",
      imo_number: "IMO9741372",
      eta: h(48),
      etd: h(110),
      container_volume: 14000,
      vessel_size: "Post-Panamax",
      priority: "Medium",
      status: "Scheduled",
      assigned_berth_id: null,
      destination: "Oakland",
      origin: "Nagoya Port",
      draft: "15.0",
      waiting_time_hours: "0.0",
    },
    {
      name: "MOL Triumph",
      imo_number: "IMO9769271",
      eta: h(54),
      etd: h(120),
      container_volume: 20170,
      vessel_size: "Ultra Large",
      priority: "High",
      status: "Scheduled",
      assigned_berth_id: null,
      destination: "Los Angeles",
      origin: "Hong Kong Port",
      draft: "16.5",
      waiting_time_hours: "0.0",
    },
    {
      name: "Golden Gate Feeder",
      imo_number: "IMO9231845",
      eta: h(-8),
      etd: h(8),
      container_volume: 2800,
      vessel_size: "Feeder",
      priority: "Low",
      status: "Loading",
      assigned_berth_id: berthMap.get("B08") || null,
      destination: "San Francisco",
      origin: "San Pedro",
      draft: "9.5",
      waiting_time_hours: "0.4",
    },
    {
      name: "Santa Barbara Express",
      imo_number: "IMO9341120",
      eta: h(-15),
      etd: h(5),
      container_volume: 3200,
      vessel_size: "Feeder",
      priority: "Low",
      status: "Completed",
      assigned_berth_id: berthMap.get("B10") || null,
      destination: "Ensenada",
      origin: "Los Angeles",
      draft: "10.0",
      waiting_time_hours: "0.2",
    },
    {
      name: "Straits Express 08",
      imo_number: "IMO9456782",
      eta: h(60),
      etd: h(124),
      container_volume: 4800,
      vessel_size: "Feeder",
      priority: "Medium",
      status: "Scheduled",
      assigned_berth_id: null,
      destination: "Mazatlan",
      origin: "Long Beach",
      draft: "11.2",
      waiting_time_hours: "0.0",
    },
  ];

  const insertedVessels = await db.insert(vessels).values(
    rawVessels.map((v) => ({
      ...v,
      port_id: portId,
    }))
  ).returning();

  const oceanStar = insertedVessels.find((v) => v.name === "MV Ocean Star");
  const cmaPalais = insertedVessels.find((v) => v.name === "CMA CGM Palais Royal");
  const hmmAlgeciras = insertedVessels.find((v) => v.name === "HMM Algeciras");
  const ooclHk = insertedVessels.find((v) => v.name === "OOCL Hong Kong");

  // 7. Congestion Predictions
  await db.insert(congestionPredictions).values([
    {
      port_id: portId,
      prediction_time: now,
      forecast_period: "24h",
      congestion_score: 84,
      risk_level: "CRITICAL",
      affected_berth: "Berths B04 & B05 (Pier G & Pier J)",
      expected_waiting_time: "5.8",
      reason:
        "Excess vessel arrivals (6 ULCVs queued simultaneously) exceeding crane discharge capacity. Yard A and Yard D approaching 90% threshold, blocking rapid offload.",
      details_json: JSON.stringify({
        breakdown: {
          vessel_load_score: 28, // /30
          berth_capacity_score: 24, // /25
          crane_availability_score: 13, // /15
          yard_utilisation_score: 14, // /15
          historical_delay_score: 11, // /15
        },
        high_risk_berths: ["B04", "B05"],
        recommended_actions: [
          "Reroute MV Ocean Star to Berth B06 (automated quay with 4 idle cranes)",
          "Reallocate Cranes C08, C09, C10 from standby to Pier E",
          "Activate Yard E rail intermodal corridor to evacuate import dwell containers",
          "Issue 6-hour delay notice for incoming feeder vessels to clear channel approach",
        ],
      }),
    },
    {
      port_id: portId,
      prediction_time: now,
      forecast_period: "48h",
      congestion_score: 72,
      risk_level: "HIGH",
      affected_berth: "Berths B01, B04, B05",
      expected_waiting_time: "4.2",
      reason:
        "Secondary wave of 4 Post-Panamax vessels scheduled while turnaround times on B04 lag behind schedule due to Crane C07 overhaul.",
      details_json: JSON.stringify({
        breakdown: {
          vessel_load_score: 22,
          berth_capacity_score: 19,
          crane_availability_score: 12,
          yard_utilisation_score: 12,
          historical_delay_score: 9,
        },
        high_risk_berths: ["B04", "B01"],
        recommended_actions: [
          "Pre-assign Madrid Maersk to Berth B06 upon arrival",
          "Double crane shifts on Berth B02 to free up quay before Day 2 peak",
        ],
      }),
    },
    {
      port_id: portId,
      prediction_time: now,
      forecast_period: "72h",
      congestion_score: 48,
      risk_level: "MEDIUM",
      affected_berth: "Berth B02, B07",
      expected_waiting_time: "2.4",
      reason:
        "Congestion steadily subsiding if recommended reroutes to Pier E automated quay are executed on schedule.",
      details_json: JSON.stringify({
        breakdown: {
          vessel_load_score: 15,
          berth_capacity_score: 14,
          crane_availability_score: 7,
          yard_utilisation_score: 8,
          historical_delay_score: 6,
        },
        high_risk_berths: ["B02"],
        recommended_actions: [
          "Resume standard preventative maintenance cycles on Cranes C13-C15",
          "Normalize gate receiving hours across Yard B export staging",
        ],
      }),
    },
  ]);

  // 8. Routing Recommendations
  if (oceanStar && berthMap.get("B04") && berthMap.get("B06")) {
    await db.insert(routingRecommendations).values([
      {
        vessel_id: oceanStar.id,
        port_id: portId,
        current_berth_id: berthMap.get("B04")!,
        recommended_berth_id: berthMap.get("B06")!,
        current_expected_wait: "5.2",
        wait_after_rerouting: "3.7",
        congestion_reduction_pct: "28.8",
        reason:
          "Berth B04 has severe backlog (96% utilisation, 0 spare cranes). Berth B06 has 4 idle high-speed STS cranes and immediate water depth clearance (17.0m). Rerouting reduces vessel wait time by 1.5 hours.",
        status: "Pending",
      },
    ]);
  }

  if (cmaPalais && berthMap.get("B05") && berthMap.get("B03")) {
    await db.insert(routingRecommendations).values([
      {
        vessel_id: cmaPalais.id,
        port_id: portId,
        current_berth_id: berthMap.get("B05")!,
        recommended_berth_id: berthMap.get("B03")!,
        current_expected_wait: "6.8",
        wait_after_rerouting: "4.1",
        congestion_reduction_pct: "39.7",
        reason:
          "Berth B05 has heavy yard staging bottleneck. Transferring partial discharge volume to Berth B03 cuts waiting by 2.7 hours and eliminates channel queue obstruction.",
        status: "Pending",
      },
    ]);
  }

  if (ooclHk && berthMap.get("B05") && berthMap.get("B06")) {
    await db.insert(routingRecommendations).values([
      {
        vessel_id: ooclHk.id,
        port_id: portId,
        current_berth_id: berthMap.get("B05")!,
        recommended_berth_id: berthMap.get("B06")!,
        current_expected_wait: "7.1",
        wait_after_rerouting: "4.8",
        congestion_reduction_pct: "32.4",
        reason:
          "Berth B06 can absorb ULCV draft requirements and provides direct dual-trolley crane automation reducing vessel turnaround by 32%.",
        status: "Pending",
      },
    ]);
  }

  // 9. Operation Plans (72-hour operational schedule)
  await db.insert(operationPlans).values([
    // TODAY
    {
      port_id: portId,
      plan_title: "Priority Vessel Clearance & Congestion Relief",
      day_label: "TODAY",
      time_slot: "08:00",
      event_type: "Berth Allocation",
      vessel_name: "MV Ocean Star",
      berth_code: "B04",
      details: "Initiate priority discharge sequence. Coordinate pilot boat escort to designated slipway.",
      priority: "Critical",
      status: "In Progress",
    },
    {
      port_id: portId,
      plan_title: "Super Post-Panamax Mooring",
      day_label: "TODAY",
      time_slot: "10:00",
      event_type: "Berth Allocation",
      vessel_name: "MSC Horizon",
      berth_code: "B02",
      details: "Finalize twin-lift discharge. Clear north apron for export consolidation tractor trains.",
      priority: "High",
      status: "Approved",
    },
    {
      port_id: portId,
      plan_title: "Automated STS Quad-Gantry Mobilisation",
      day_label: "TODAY",
      time_slot: "12:00",
      event_type: "Crane Allocation",
      vessel_name: "MV Ocean Star",
      berth_code: "B06",
      details: "Deploy Cranes C08, C09, C10, C11 in tandem mode. Target 140 moves/hour net crane rate.",
      priority: "High",
      status: "Approved",
    },
    {
      port_id: portId,
      plan_title: "Congestion Bypass Rerouting",
      day_label: "TODAY",
      time_slot: "15:00",
      event_type: "Vessel Rerouting",
      vessel_name: "CMA CGM Palais Royal",
      berth_code: "B03",
      details: "Execute dynamic diversion from congested Berth B05 to Berth B03. Expected saving: 2.7 hrs.",
      priority: "Critical",
      status: "Approved",
    },
    {
      port_id: portId,
      plan_title: "Yard Rail Intermodal Evacuation",
      day_label: "TODAY",
      time_slot: "18:00",
      event_type: "Yard Redistribution",
      vessel_name: "All Berth 04 Inbound",
      berth_code: "YARD-A",
      details: "Dispatch 1,200 TEU import dwell containers to Yard E rail spur to alleviate Yard A congestion.",
      priority: "High",
      status: "Approved",
    },

    // TOMORROW
    {
      port_id: portId,
      plan_title: "ULCV Morning Arrival Handling",
      day_label: "TOMORROW",
      time_slot: "08:00",
      event_type: "Berth Allocation",
      vessel_name: "Maersk Mc-Kinney Moller",
      berth_code: "B01",
      details: "Secure starboard alongside. Synchronize lashers and shore crane operators on 3 shifts.",
      priority: "High",
      status: "Approved",
    },
    {
      port_id: portId,
      plan_title: "Yard Consolidation & Reefer Check",
      day_label: "TOMORROW",
      time_slot: "11:00",
      event_type: "Yard Redistribution",
      vessel_name: "Yard C & Yard B",
      berth_code: "YARD-C",
      details: "Balance empty container stacks at Yard D; re-plug 420 reefer units for export validation.",
      priority: "Normal",
      status: "Approved",
    },
    {
      port_id: portId,
      plan_title: "Crane Heavy Lift Reconfiguration",
      day_label: "TOMORROW",
      time_slot: "14:00",
      event_type: "Crane Allocation",
      vessel_name: "COSCO Shipping Universe",
      berth_code: "B04",
      details: "Shift Cranes C01 & C02 to bays 34-48 for oversized 40ft high-cube container discharge.",
      priority: "High",
      status: "Approved",
    },
    {
      port_id: portId,
      plan_title: "Feeder Transshipment Connection",
      day_label: "TOMORROW",
      time_slot: "17:00",
      event_type: "Berth Allocation",
      vessel_name: "Wan Hai 515",
      berth_code: "B08",
      details: "Direct cross-dock loading from B02 arrivals onto regional feeder vessel.",
      priority: "Normal",
      status: "Approved",
    },

    // DAY 3
    {
      port_id: portId,
      plan_title: "Quay Crane Overhaul & Certification",
      day_label: "DAY 3",
      time_slot: "09:00",
      event_type: "Maintenance",
      vessel_name: "Crane C07 Inspection",
      berth_code: "B09",
      details: "Complete wire rope replacement and spreader safety sensor calibration on STS Crane C07.",
      priority: "High",
      status: "Approved",
    },
    {
      port_id: portId,
      plan_title: "Scheduled Mega-Vessel Reception",
      day_label: "DAY 3",
      time_slot: "13:00",
      event_type: "Berth Allocation",
      vessel_name: "Madrid Maersk",
      berth_code: "B06",
      details: "Docking at Pier E automated facility. Full automated guided vehicle (AGV) support allocated.",
      priority: "Critical",
      status: "Approved",
    },
    {
      port_id: portId,
      plan_title: "Night Shift Throughput Maximization",
      day_label: "DAY 3",
      time_slot: "20:00",
      event_type: "Crane Allocation",
      vessel_name: "HMM Algeciras",
      berth_code: "B05",
      details: "Triple gantry crane assignment to achieve vessel turnaround target of 32 hours.",
      priority: "High",
      status: "Approved",
    },
  ]);

  // 10. Alerts
  await db.insert(alerts).values([
    {
      port_id: portId,
      title: "HIGH CONGESTION WARNING: Pier G & Pier J",
      message:
        "High congestion expected at Berth B04 and B05 within 6 hours. Current queue index at 84/100 (CRITICAL). 6 ULCVs are waiting offshore.",
      severity: "CRITICAL",
      category: "HIGH CONGESTION WARNING",
      is_read: false,
    },
    {
      port_id: portId,
      title: "VESSEL DELAY: CMA CGM Rivoli",
      message:
        "MV CMA CGM Rivoli is delayed by 8.3 hours waiting in outer anchorage due to berth occupation at B05.",
      severity: "HIGH",
      category: "VESSEL DELAY",
      is_read: false,
    },
    {
      port_id: portId,
      title: "BERTH OVERLOAD: Berth B04 at 96% Capacity",
      message:
        "Berth B04 operational utilization has reached 96%. Immediate vessel discharge bottlenecks anticipated.",
      severity: "HIGH",
      category: "BERTH OVERLOAD",
      is_read: false,
    },
    {
      port_id: portId,
      title: "ALTERNATE ROUTE RECOMMENDED: MV Ocean Star",
      message:
        "Recommended rerouting MV Ocean Star from B04 to B06 may reduce expected waiting time by 28.8% (saving 1.5 hrs).",
      severity: "MEDIUM",
      category: "ALTERNATE ROUTE RECOMMENDED",
      is_read: false,
    },
    {
      port_id: portId,
      title: "YARD CAPACITY WARNING: Yard A at 90% Occupancy",
      message:
        "Import staging Yard A occupancy has exceeded 90% (31,500/35,000 TEU). Divert inbound containers to Yard E rail spur.",
      severity: "HIGH",
      category: "YARD CAPACITY WARNING",
      is_read: false,
    },
    {
      port_id: portId,
      title: "CRANE SHORTAGE: Berths B04 & B05",
      message:
        "Zero spare STS cranes available at Pier G. Crane C07 scheduled maintenance is reducing overall throughput by 46 moves/hr.",
      severity: "MEDIUM",
      category: "CRANE SHORTAGE",
      is_read: false,
    },
    {
      port_id: portId,
      title: "MAINTENANCE WARNING: Crane C07 Spreader Calibration",
      message:
        "STS Crane C07 is undergoing wire rope and spreader calibration. Return to service estimated in 36 hours.",
      severity: "LOW",
      category: "MAINTENANCE WARNING",
      is_read: true,
    },
  ]);

  console.log("Seeding complete successfully!");
}
